os: linux
dist: xenial
cache: pip
language: python
python:
  - "3.8"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt
  - pip install --upgrade pip setuptools wheel
install:
  - pip install -q -r requirements.txt
  - conda install --yes -c plotly plotly-orca
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - |
    set -e
    for n in */*.ipynb
    do
      travis_wait 180 jupyter nbconvert --to notebook --execute $n
    done
env:
  - GEOMSTATS_BACKEND=numpy
